name: Cabal Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.7', '9.0.1']
        cabal: ['3.4']
        os: ['ubuntu-20.04']
        with_aeson: ['-with-aeson', '+with-aeson']
        with_configuration_tools: ['-with-configuration-tools', '+with-configuration-tools']
        with_quickcheck: ['-with-quickcheck', '+with-quickcheck']
        include:
        - ghc: '8.8.4'
          cabal: '3.4'
          os: 'ubuntu-20.04'
          with_aeson: '+with-aeson'
          with_configuration_tools: '+with-configuration-tools'
          with_quickcheck: '+with-quickcheck'
        - os: 'macOS-latest'
          ghc: '8.10.7'
          cabal: '3.4'
          with_aeson: '+with-aeson'
          with_configuration_tools: '+with-configuration-tools'
          with_quickcheck: '+with-quickcheck'

        # for now, only do minimal default build on windows
        - os: 'windows-latest'
          ghc: '8.10.7'
          cabal: '3.4'
          with_aeson: '+with-aeson'
          with_configuration_tools: '+with-configuration-tools'
          with_quickcheck: '+with-quickcheck'

    steps:
    # Setup
    - name: Checkout repository
      uses: actions/checkout@v2

    # Haskell Setup
    - name: Install GHC and Cabal
      uses: larskuhtz/actions/setup@e0f107055073590682bc5264b8da5c2b6af39a65
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}

    # Restore Packages from Caches
    - uses: pat-s/always-upload-cache@v2.1.5
      name: Cache dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-0-cabal

    # Local cabal config
    - name: Create local cabal config
      shell: bash
      run: |
        cat > cabal.project.local <<EOF
        package hostaddress
          documentation: True
          benchmarks: True
          tests: True
          flags: ${{ matrix.with_aeson }} ${{ matrix.with_configuration_tools }} ${{ matrix.with_quickcheck }}
        package configuration-tools
          flags: -remote-configs
        EOF

    # Build
    - name: Update package database
      run: cabal update
    - name: Build
      run: cabal build
    - name: Check
      run: cabal check
    - name: build distribution package
      run: cabal sdist
